version: "3"
services:
  catalog:
    build: .
    restart: always
    ports:
      - "5353:4848"
      - "9005:8080"
    networks:
      synchronicity:
        aliases:
          - catalog.docker
    volumes:
      - ./apis-config:/etc/default/tmf/
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_HOST=mysql

volumes:
  mysql-catalog-data:

networks:
  synchronicity:
    external: true
